FROM docker.elastic.co/elasticsearch/elasticsearch:6.5.2

ARG USER_ID=
ARG GROUP_ID=
ARG USER=
ARG GROUP=

ENV ES_HOME=/usr/share/elasticsearch
ENV ElASTICSEARCH_HOME=/usr/share/elasticsearch

# configure container permissions
RUN groupadd -g ${GROUP_ID} ${GROUP} && \
    useradd -l -u ${USER_ID} -g ${GROUP} ${USER}

COPY elasticsearch.yml ./config/

RUN chown --no-dereference --recursive ${USER}:${GROUP} \
        /usr/share/elasticsearch \
        ./

USER ${USER}