FROM docker.elastic.co/kibana/kibana:6.5.2


ARG USER_ID=1001
ARG GROUP_ID=1001
ARG USER=
ARG GROUP=

# increase node heap size
# ENV NODE_OPTIONS="--max-old-space-size=4096"

USER root

# configure container permissions
RUN groupadd -g ${GROUP_ID} ${GROUP} && \
    useradd -l -u ${USER_ID} -g ${GROUP} ${USER}

COPY kibana.yml ./config/

RUN chown --no-dereference --recursive ${USER}:${GROUP} \
        /usr/share/kibana \
        ./

USER ${USER}